namespace CCreative.Compilers.Enums;

public enum ClassifierType
{
	None,

	Comment,
	ExcludedCode,
	Identifier,
	Keyword,
	ControlKeyword,
	NumericLiteral,
	Operator,
	OperatorOverloaded,
	PreprocessorKeyword,
	StringLiteral,
	WhiteSpace,
	Text,

	StaticSymbol,

	PreprocessorText,
	Punctuation,
	VerbatimStringLiteral,
	StringEscapeCharacter,

	ClassName,
	RecordClassName,
	RecordStructName,
	DelegateName,
	EnumName,
	InterfaceName,
	ModuleName,
	StructName,
	TypeParameterName,

	FieldName,
	EnumMemberName,
	ConstantName,
	LocalName,
	ParameterName,
	MethodName,
	ExtensionMethodName,
	PropertyName,
	EventName,
	NamespaceName,
	LabelName,

	XmlDocCommentAttributeName,
	XmlDocCommentAttributeQuotes,
	XmlDocCommentAttributeValue,
	XmlDocCommentCDataSection,
	XmlDocCommentComment,
	XmlDocCommentDelimiter,
	XmlDocCommentEntityReference,
	XmlDocCommentName,
	XmlDocCommentProcessingInstruction,
	XmlDocCommentText,

	XmlLiteralAttributeName,
	XmlLiteralAttributeQuotes,
	XmlLiteralAttributeValue,
	XmlLiteralCDataSection,
	XmlLiteralComment,
	XmlLiteralDelimiter,
	XmlLiteralEntityReference,
	XmlLiteralName,
	XmlLiteralProcessingInstruction,
	XmlLiteralText,

	RegexComment,
	RegexCharacterClass,
	RegexAnchor,
	RegexQuantifier,
	RegexGrouping,
	RegexAlternation,
	RegexText,
	RegexSelfEscapedCharacter,
	RegexOtherEscape,

	Number,
}